aliases:
  - &restore_test_cache
    keys:
      - test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}

  - &save_test_cache
    paths:
      - ./node_modules
    key: test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}

  - &save_test_cache
    paths:
      - ./node_modules
    key: test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}

  - &install_npm
    name: install dependencies
    command: |
      npm install

  - &defaults
    working_directory: ~/project
    docker:
      - image: circleci/node:8

  - &build_package
    name: build package
    command: |
      npm run build

  - &test_with_coverage
    name: test
    command: npm run test-with-coverage

  - &filter_common
    branches:
      ignore: gh-pages
    tags:
      ignore: /.*/

version: 2
jobs:
  node_v8:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore_test_cache
      - run: *install_npm
      - save_cache: *save_test_cache
      - run: *build_package
      - run: *test_with_coverage
      - store_test_results:
          path: coverage

  node_v10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: *install_npm
      - run: *build_package
      - run: *test_with_coverage

workflows:
  version: 2
  dev-builds:
    jobs:
      - node_v8:
          filters: *filter_common
      - node_v10:
          filters: *filter_common