aliases:
  - &restore_test_cache
    keys:
      - test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}

  - &save_test_cache
    paths:
      - ./node_modules
    key: test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}

  - &save_test_cache
    paths:
      - ./node_modules
    key: test-{{ .Environment.PROJECT_CACHE_VERSION }}-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}

  - &install_npm
    name: install dependencies
    command: |
      npm install

  - &defaults
    working_directory: ~/project
    docker:
      - image: circleci/node:8

  - &build_package
    name: build package
    command: |
      npm run build

  - &test_with_coverage
    name: test
    command: npm run test-with-coverage

  - &filter_common
    branches:
      ignore: gh-pages
    tags:
      ignore: /.*/

  - &filter_tag_all
    tags:
      only: /^v.*/
    branches:
      ignore: /.*/

  - &filter_tag_stable
    tags:
      only: /^v[0-9]+(\.[0-9]+)*$/
    branches:
      ignore: /.*/

version: 2
jobs:
  node_v8:
    <<: *defaults
    steps:
      - checkout
      - restore-cache: *restore_test_cache
      - run: *install_npm
      - save_cache: *save_test_cache
      - run: *build_package
      - run: *test_with_coverage
      - store_test_results:
          path: coverage
      - persist_to_workspace:
          root: .
          paths:
            - lib

  node_v10:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: *install_npm
      - run: *build_package
      - run: *test_with_coverage

  publish-github-release:
    docker:
      - image: cibuilds/github:0.12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            VERSION=${CIRCLE_TAG}
            echo "Naman"
            echo ${CIRCLE_TAG}
            echo "Aggarwal"
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete v0.1 ./lib/


workflows:
  version: 2
  dev-builds:
    jobs:
      - node_v8:
          filters: *filter_common
      - node_v10:
          filters: *filter_common
  prod-builds:
    jobs:
      - node_v8:
          filters: *filter_tag_all
      - node_v10:
          filters: *filter_tag_all
      - publish-github-release:
          requires:
            - node_v8
            - node_v10
          filters: *filter_tag_stable
